train:
  _target_: src.data_module.dataset.DiffusionTrackerDataset
  waymax_conf_version: WOD_1_3_1_TRAINING
  gs_path: "gs://waymo_open_dataset_motion_v_1_3_1/uncompressed/tf_example/training/training_tfexample.tfrecord@"
  num_states: 100
  max_num_objects: 32
  start_ind: 200
  # download_path: "data/train"
  download_path: null
val:
  _target_: src.data_module.dataset.DiffusionTrackerDataset
  waymax_conf_version: WOD_1_3_1_TRAINING
  gs_path: "gs://waymo_open_dataset_motion_v_1_3_1/uncompressed/tf_example/training/training_tfexample.tfrecord@"
  num_states: 100
  max_num_objects: 32
  start_ind: 0
  # download_path: "data/val"
  download_path: null
test:
  _target_: src.data_module.dataset.DiffusionTrackerDataset
  waymax_conf_version: WOD_1_3_1_TRAINING
  gs_path: "gs://waymo_open_dataset_motion_v_1_3_1/uncompressed/tf_example/training/training_tfexample.tfrecord@"
  num_states: 100
  max_num_objects: 32
  start_ind: 100
  # download_path: "data/test"
  download_path: null
