_target_: src.data_module.DiffusionTrackerDataset
waymax_config: waymax.config.WOD_1_3_1_TRAINING
gs_path: "gs://waymo_open_dataset_motion_v_1_3_1/uncompressed/tf_example/training/training_tfexample.tfrecord@"
max_num_states: 10
max_num_objects: None
download: False
gcloud_token: None
