train:
  - _target_: src.metrics.AdeMetric
    name: ADE
  - _target_: src.metrics.FdeMetric
    name: FDE
val:
  - _target_: src.metrics.AdeMetric
    name: ADE
  - _target_: src.metrics.FdeMetric
    name: FDE
