_target_: src.models.DiffusionAttentionModel
seed: ${trainer.seed}
load_best_checkpoint: ${trainer.load_best_checkpoint}
cfg_metrics: ${metrics}
grad_clip: ${trainer.gradient_clip_val}
vis_cfg: ${visual}
trainer_cfg: ${trainer}
prediction_target: x0
lr: 1e-3
lr_scheduler:
  name: cosine
  decay_steps: 230
  end_lr: 7e-4
oracle_cfg:
  use_for_train_loss: false
  use_for_val_loss: false
  use_for_sampling: false
  sampling_mode: exact
  sampling_t0: 0.001
num_agents: 32
time_len: 11
num_feat: 9
se_args:
  rnn_type: "mhsa" # one of "lstm" "mhsa"
  rnn_num_heads: 1
  sa_num_heads: 1
  drop_attn: 0.1
  mlp_dim: 60
  num_mlp_layers: 2
  num_agents: ${model.num_agents}
  time_len: ${model.time_len}
  num_feat: ${model.num_feat}
  out_dim: 40
  pos_emb_type: "lookup" #one of "rope", "lookup", "None"
  rope_theta: 0.1
samlp_args:
  attn_dim: 160
  attn_num_heads: 1
  mlp_dim: 60
  num_mlp_layers: 1
  drop_attn: 0.1
  out_dim: 160
num_sa_mlp: 2
camlp_args:
  attn_dim: 160
  attn_num_heads: 1
  mlp_dim: 60
  num_mlp_layers: 1
  drop_attn: 0.1
  out_dim: 160
  kv_dim: 40
num_camlp: 4
output_shape: [32, 80, 2]
fourier_num_freqs: 80
final_out_dim: 160
