_target_: src.models.DiffusionAttentionModel
seed: ${trainer.seed}
load_last_checkpoint: ${trainer.load_last_checkpoint}
cfg_metrics: ${metrics}
grad_clip: ${trainer.gradient_clip_val}
vis_cfg: ${visual}
num_agents: 32
time_len: 10
num_feat: 2
se_args:
  rnn_type: "mhsa" # one of "lstm" "mhsa"
  rnn_num_heads: 1
  sa_num_heads: 1
  drop_attn: 0.1
  mlp_dim: 30
  num_mlp_layers: 2
  num_agents: ${model.num_agents}
  time_len: ${model.time_len}
  num_feat: ${model.num_feat}
  out_dim: 20
  pos_emb_type: "lookup" #one of "rope", "lookup", "None"
  rope_theta: 0.1
samlp_args:
  attn_dim: 164 #2*(time_future+1)
  attn_num_heads: 1
  mlp_dim: 30
  num_mlp_layers: 1
  drop_attn: 0.1
  out_dim: 164
num_sa_mlp: 1
camlp_args:
  attn_dim: 164 #2*(time_future+1)
  attn_num_heads: 1
  mlp_dim: 30
  num_mlp_layers: 1
  drop_attn: 0.1
  out_dim: 164
  kv_dim: 20
final_out_dim: 162
num_camlp: 2
output_shape: [32, 81, 2]
