_target_: src.models.DiffusionLinearModel
seed: ${trainer.seed}
load_last_checkpoint: ${trainer.load_last_checkpoint}
cfg_metrics: ${metrics}
grad_clip: ${trainer.gradient_clip_val}
vis_cfg: ${visual}
hid_dim: 256
input_shape: [32, 20]
output_shape: [32, 162]
