_target_: src.models.diff_attn._DiffusionAttentionBase
seed: ${trainer.seed}
load_best_checkpoint: ${trainer.load_best_checkpoint}
cfg_metrics: ${metrics}
grad_clip: ${trainer.gradient_clip_val}
vis_cfg: ${visual}
trainer_cfg: ${trainer}
prediction_target: x0
num_agents: 32
time_len: 11
num_feat: 9
se_args:
  rnn_type: "mhsa" # one of "lstm" "mhsa"
  rnn_num_heads: 1
  sa_num_heads: 1
  drop_attn: 0.1
  mlp_dim: 30
  num_mlp_layers: 2
  num_agents: ${model.num_agents}
  time_len: ${model.time_len}
  num_feat: ${model.num_feat}
  out_dim: 20
  pos_emb_type: "lookup" #one of "rope", "lookup", "None"
  rope_theta: 0.1
samlp_args:
  attn_dim: 160
  attn_num_heads: 1
  mlp_dim: 30
  num_mlp_layers: 1
  drop_attn: 0.1
  out_dim: 160
num_sa_mlp: 1
camlp_args:
  attn_dim: 160
  attn_num_heads: 1
  mlp_dim: 30
  num_mlp_layers: 1
  drop_attn: 0.1
  out_dim: 160
  kv_dim: 20
num_camlp: 2
output_shape: [32, 80, 2]
fourier_num_freqs: 80
final_out_dim: 160
model:
  _target_: src.models.diff_attn.DiffAttention
  se_args: ${model.se_args}
  samlp_args: ${model.samlp_args}
  num_sa_mlp: ${model.num_sa_mlp}
  camlp_args: ${model.camlp_args}
  num_camlp: ${model.num_camlp}
  out_shape: ${model.output_shape}
  final_out_dim: ${model.final_out_dim}
loss:
  _target_: src.losses.MSELoss
optimizer:
  _target_: optax.adam
scheduler:
  _target_: optax.cosine_decay_schedule
  init_value: 1e-3
  decay_steps: 230
  alpha: 0.7
