defaults:
  - model: diffusion_linear
  - dataloaders: basic
  - data: processed_v1
  - transforms: null
  - logger: clearml
  - metrics: all_metrics
  - visual: default
  - _self_
trainer:
  num_epochs: 100
  train_epoch_len: 100
  val_epoch_len: 10
  gradient_clip_val: 6.0
  log_every_n_steps: 10
  seed: 1
  val_batches: 4
  train_metric_batches: 3
  val_metric_batches: 3
  train_metric_every_n_epochs: 1
  val_metric_every_n_epochs: 1
  check_val_every_n_epoch: 1
  samples_per_scene: 1
  generate_every_epoch: 1
  print_hparams: True
  logging: "offline"
  load_last_checkpoint: False
