defaults:
  - model: diffusion_model
  - dataloaders: basic
  - datasets: basic
  - transforms: null
  - logger: wandb
  - metrics: all_metrics
  - _self_
trainer:
  num_epochs: 10
  train_epoch_len: 100
  val_epoch_len: 10
  gradient_clip_val: 6.0
  log_every_n_steps: 10
  seed: 1
  enabled: True
  val_batches: 4
  samples_per_scene: 1
  generate_every_epoch: 1
logging: "offline"
