defaults:
  - model: diffusion_attn
  - dataloaders: overfit
  - dataset: small_no_scenes
  - logger: clearml
  - metrics: all_metrics
  - visual: default
  - diffusion_sampler: ddpm
  - losses: mse_action_full
  - _self_

trainer:
  train_mode: "train"
  num_agents: 32
  action_len: ${losses.action_len}
  extract_actions: ${losses.extract_actions}
  enable_profiler: false
  limit_profile_batches: 10
  debug: false
  num_epochs: 41
  train_epoch_len: 1.0
  val_epoch_len: 1.0
  log_validation: true
  grad_clip: 5.0
  seed: 1
  check_val_every_n_epoch: 1
  log_metrics_every_batch: 10
  train_metric_every_n_epochs: 5
  max_train_metric_batches: 12
  print_hparams: False
  logging: "online"
  best_checkpoint_metric: "val/loss"
  best_checkpoint_mode: "min"
  load_best_checkpoint: true
  run_test_after_fit: false
  test_with_best_checkpoint: true

dataset:
  data:
    s3_url: null
    data_access: null

loss: ${losses.loss}

optimizer:
  _target_: optax.adamw
  weight_decay: 0.0001

scheduler:
  _target_: optax.cosine_decay_schedule
  init_value: 5e-3
  decay_steps: 650
  alpha: 0.01
