defaults:
  - model: diffusion_attn
  - dataloaders: basic
  - feat_extract: small_no_scenes
  - transforms: null
  - logger: clearml
  - metrics: all_metrics #TODO Did we fix all metrics?
  - visual: default #TODO Why default here?
  - diffusion_sampler: ddpm
  - _self_
trainer:
  num_epochs: 150
  train_epoch_len: 1.0
  val_epoch_len: 1.0
  gradient_clip_val: 5.0
  log_every_n_steps: 10
  seed: 1
  train_metric_batches: 1
  val_metric_batches: 1
  train_metric_every_n_epochs: 20
  val_metric_every_n_epochs: 20
  check_val_every_n_epoch: 1
  samples_per_scene: 1
  generate_every_epoch: 0
  print_hparams: False
  logging: "offline"
  load_best_checkpoint: False

  enable_profiler: False
  enable_jax_profiler: False
  jax_profiler_dir: null
  jax_profiler_start_step: 2
  jax_profiler_num_steps: 3
  proxy_val_loss:
    enabled: false
    step_stride: 5
    include_last: true

prediction_target: x0
t0: 1e-3
t1: 2.0
dt0: 0.01

loss:
  _target_: src.losses.MSELoss

optimizer:
  _target_: optax.adam

scheduler:
  _target_: optax.cosine_decay_schedule
  init_value: 1e-3
  decay_steps: 230
  alpha: 0.7
