defaults:
  - model: diffusion_attn_2x
  - dataloaders: basic
  - datasets: basic
  - transforms: null
  - logger: wandb
  - metrics: all_metrics
  - visual: default
  - _self_
trainer:
  num_epochs: 230
  train_epoch_len: 1
  val_epoch_len: 1
  gradient_clip_val: 5.0
  log_every_n_steps: 10
  seed: 1
  val_batches: 4
  samples_per_scene: 1
  generate_every_epoch: 0
  print_hparams: True
  logging: "offline"
  load_last_checkpoint: False
