# passed to plot_simulator_state(...)
use_log_traj: true
highlight_obj: SDC
plot_all_trajectories: true

pred_alpha: 0.8
pred_linewidth: 2.0
pred_linestyle: "-"
pred_clip_to_view: true
gt_linewidth: 0.85
pred_raw_plot: true
debug_metrics: false
debug_denoiser_scale: false
direct_prediction_eval: false
num_trajectory_samples: 1
sample_steps: 1
enable_visualization: false
enable_train_visualization: false

# passed into Waymax VizConfig(**viz_config)
viz_config:
  show_agent_id: false
  center_agent_idx: -1
  back_x: 75
  front_x: 75
  back_y: 75
  front_y: 75
