# @package _global_
dataset_creation:
  train:
    raw_data_url: "gs://waymo_open_dataset_motion_v_1_3_1/uncompressed/tf_example/training/training_tfexample.tfrecord@1000"
    waymax_conf_version: "WOD_1_3_1_TRAINING"
    num_states: 10
    max_num_objects: 32
    extract_scene: true
    preprocessing:
      max_polylines: 256
      current_index: 10
      num_points_polyline: 30
      use_log: true
      remove_history: false
  val:
    raw_data_url: "gs://waymo_open_dataset_motion_v_1_3_1/uncompressed/tf_example/validation/validation_tfexample.tfrecord@150"
    waymax_conf_version: "WOD_1_3_1_TRAINING"
    num_states: 2
    max_num_objects: 32
    extract_scene: true
    preprocessing:
      max_polylines: 256
      current_index: 10
      num_points_polyline: 30
      use_log: true
      remove_history: false
  test:
    raw_data_url: "gs://waymo_open_dataset_motion_v_1_3_1/uncompressed/tf_example/testing/testing_tfexample.tfrecord@150"
    waymax_conf_version: "WOD_1_3_1_TRAINING"
    num_states: 5
    max_num_objects: 32
    extract_scene: true
    preprocessing:
      max_polylines: 256
      current_index: 10
      num_points_polyline: 30
      use_log: true
      remove_history: false
